title: Lemon Productions
baseURL: /
params:
  palette: blue
  header:
    title: Lemon Productions
    logo_img: images/logo.png
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: Features
        url: /features
      - label: Pricing
        url: /pricing
      - label: Style Guide
        url: /style-guide
      - label: Newsletter
        url: /newsletter
        primary: true
  footer:
    logo_img: images/logo_alt.png
    tagline: SaaS theme by Stackbit
    has_nav: true
    nav_title: Company
    nav_links:
      - label: About Us
        url: /about
      - label: Blog
        url: /blog
      - label: Sign Up
        url: signup
      - label: Contact
        url: /contact
    has_social: true
    social_title: Social
    social_links:
      - label: Twitter
        url: 'https://twitter.com/lemonproduction'
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/lemonproductionsca'
        new_window: true
      - label: YouTube
        url: 'https://www.youtube.com/c/lemonproductionsca'
        new_window: true
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    content: '&copy; Lemon Productions. All rights reserved.'
    links:
      - label: Made with Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
